### ISSUE TITLE
Cannot uninstall/reinstall deluge 

### ISSUE THREAD

**Issue by silkyclouds** [TechPerplexed/GooPlex#1]
Hello there,

I would like to reinstall deluge as it is unfotunately not reachable through its web interface anymore (while the daemon is running). 

How can I achieve this ? 

thanks !!! Gooplex is really a nice set of tools / apps !

**Comment by TechPerplexed** [comment]
Glad you like it :)

Did you try `sudo apt-get remove --purge deluge` to uninstall Deluge?

**Comment by silkyclouds** [comment]
hey there,

Of course I did it ;) 

But -> Package 'deluge' is not installed, so not removed

If I do : systemctl status deluged though : 

Loaded: loaded (/etc/systemd/system/deluged.service; enabled; vendor preset: 
   Active: active (running)

Gooplex also see it running and installed and won't let me reinstall it. any clue how this could be ? :/

**Comment by TechPerplexed** [comment]
Make sure the port is open. I'm currently traveling but from memory: `sudo ufw allow 8112'

**Comment by silkyclouds** [comment]
port is open. 

*:8112 :S

**Comment by TechPerplexed** [comment]
Apologies for the late reply, I'm back from my travels and can gradually start to give things my undivided attention again. Did you have any luck solving this?

**Comment by TechPerplexed** [comment]
Going to close this as it's been two weeks since your last reply... feel free to open a new issue if you still have difficulties :)
