### ISSUE TITLE
After updating gooplex it doesnt' work anymore

### ISSUE THREAD

**Issue by Ammiraglio** [TechPerplexed/GooPlex#2]
Hello, thanks for the tool, it was very helpful.
Today after I launched gooplex I choose the option to update gooplex itself and now when I type gooplex i get this message: /bin/gooplex: line 15: /opt/GooPlex/menus/main.sh: No such file or directory
It seems the /opt/GooPlex directory got deleted.

**Comment by TechPerplexed** [comment]
Weird, I can't reproduce this. Can you try to install it from scratch again?

**Comment by Ammiraglio** [comment]
Wouldn't it mess up my configuration if I run the installation again? (sudo wget https://files.techperplexed.ga/install.sh -O /tmp/install.sh && sudo bash /tmp/install.sh)

After I installed and configured the apps I was using gooplex only for the script that backup plex and tautulli, but I can do that manually without anyproblem.

**Comment by TechPerplexed** [comment]
No, running the installation again won't mess up anything, it will just redownload the files.

**Comment by Ammiraglio** [comment]
Ok after reinstalling I chose not to creat user plexuser as it already exists.
Now gooplex works.

**Comment by TechPerplexed** [comment]
Perfect, glad you got it resolved!
