### ISSUE TITLE
Request: Add support for Ombi

### ISSUE THREAD

**Issue by english06** [TechPerplexed/GooPlex#3]
https://github.com/tidusjar/Ombi

This would fit nicely amongst this suite of tools.

**Comment by deedeefink** [comment]
+1

**Comment by TechPerplexed** [comment]
Thanks, I'll definitely consider it :)

**Comment by TechPerplexed** [comment]
Done! Give it a whirl at YourIP:5000

**Comment by TechPerplexed** [comment]
Ok, I'm going to close this thread now... app is implemented. Feel free to open a new thread if there are any issues :)
