### ISSUE TITLE
Request: Suggestions for further development

### ISSUE THREAD

**Issue by deedeefink** [TechPerplexed/GooPlex#4]
Thanks for the great work already. I got a beautiful system up and running thanks to Gooplex.

1. Add support option for NginX with reverse proxy and Let's encrypt
2. +1 for Ombi support (https://github.com/TechPerplexed/GooPlex/issues/3)
3. Backup of all Gooplex offered apps/services to Google Drive (Rclone)

Thanks

P.s.
This is the guide I used for Nginx reverse proxy with Let's encrypt: https://www.htpcguides.com/secure-nginx-reverse-proxy-with-lets-encrypt-on-ubuntu-16-04-lts/

**Comment by TechPerplexed** [comment]
Thanks for the suggestions! Idea #2 is still being worked on, #3 is a good addition. I'll consider it.

As for #1, I can't promise anything... I'm not that tech savvy. Unless someone is willing to assist :)

**Comment by TechPerplexed** [comment]
It's been a while... but I'm happy to say that Ombi is now supported.

Stay tuned for a complete overhaul which will include reverse proxy and a full backup... hopefully later this year!

Closing this thread now, feel free to open a new one if you encounter any issues or if you have more suggestions :)
