### ISSUE TITLE
Request: Any chance for NZBGet support?

### ISSUE THREAD

**Issue by ElPedroRL** [TechPerplexed/GooPlex#5]
For us who don't use torrents?

**Comment by ElPedroRL** [comment]
@TechPerplexed

**Comment by TechPerplexed** [comment]
Apologies for the late reply! I'll see what can be done - no promises though :D

**Comment by daicain** [comment]
Would like to have this added as well +1

**Comment by TechPerplexed** [comment]
It's been added guys - I haven't got a Usenet account, so I can't test this... please update GooPlex (option E - then A) and try it. 

The address is YourIP:6790

**Comment by TechPerplexed** [comment]
Ok, I'm going to close this thread now... app is implemented. Feel free to open a new thread if there are any issues :)
